CREATE DATABASE crud_alunos;

USE crud_alunos;

CREATE TABLE alunos (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  address VARCHAR(50) NOT NULL,
  neighborhood VARCHAR(50) NOT NULL,
  city VARCHAR(50) NOT NULL,
  number INT NOT NULL,
  cep VARCHAR(9) NOT NULL,
  complement VARCHAR(50),
  state VARCHAR(50) NOT NULL
);